name: Call a Re-Useable Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  coder-aws-vm-linux:
    uses: jatcod3r/modules/.github/workflows/tf-cicd.yaml
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

