name: Call a Re-Useable Workflow

on: push
  # pull_request:
  #   branches:
  #     - master

jobs:
  login:
    uses: ./.github/workflows/setup.yaml
    permissions: 
      id-token: write
      contents: read
    secrets:
      default-role: ${{ secrets.DEFAULT_ROLE }}
      default-region: ${{ secrets.DEFAULT_REGION }}
      s3-profile-name: demo-profile
      s3-role: ${{ secrets.S3_ROLE }}
      s3-region: ${{ secrets.S3_REGION }}
  
  coder-aws-vm-linux:
    uses: ./.github/workflows/tf-cicd.yaml
    needs: [login]
    permissions:
      id-token: write
      issues: write
      contents: read
    with:
      working-directory: ./coder/template/coder-aws-vm-linux

