name: Test Modules

on: push
  # pull_request:
  #   branches:
  #     - master

jobs:
  template-coder-aws-vm-linux:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
      pull-requests: write
    with:
      working-directory: ./coder/template/coder-aws-vm-linux
      module-name: coder-aws-vm-linux
    secrets: inherit
  template-coder-aws-vm-mac:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
      pull-requests: write
    with:
      working-directory: ./coder/template/coder-aws-vm-mac
      module-name: coder-aws-vm-mac
      ENV_VARS: |
        TF_VAR_ec2_user_password=MockP@ssw0rd1234!
    secrets: inherit
  template-coder-aws-vm-win:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
      pull-requests: write
    with:
      working-directory: ./coder/template/coder-aws-vm-win
      module-name: coder-aws-vm-win
    secrets: inherit