name: Call a Re-Useable Workflow

on: push
  # pull_request:
  #   branches:
  #     - master

jobs:
  template-coder-aws-vm-linux:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
    with:
      working-directory: ./coder/template/coder-aws-vm-linux
    secrets: inherit
  template-coder-aws-vm-mac:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
    with:
      working-directory: ./coder/template/coder-aws-vm-mac
    secrets: inherit
  template-coder-aws-vm-win:
    uses: ./.github/workflows/tf-cicd.yaml
    permissions:
      id-token: write
      issues: write
      contents: read
    with:
      working-directory: ./coder/template/coder-aws-vm-win
    secrets: inherit