name: TF CI/CD

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      default-audience:
        type: string
        default: sts.amazonaws.com
        required: false
      s3-profile-name:
        type: string
        required: true
      s3-profile-web-token-path:
        type: string
        default: /tmp/web_identity_token_file
        required: false
    secrets: 
      default-role:
        required: true
      default-region:
        required: true
      s3-role:
        required: true
      s3-region:
        required: true

jobs: 
  tf-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup-default-profile
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        audience: ${{ inputs.default-audience }}
        aws-region: ${{ secrets.default-region }}
        role-to-assume: ${{ secrets.default-role }}

    - name: setup-s3-profile
      run: |
          aws configure set region ${{ secrets.s3-region }} --profile ${{ inputs.s3-profile-name }}
          aws configure set role_arn ${{ secrets.s3-role }} --profile ${{ inputs.s3-profile-name }}
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > ${{ inputs.s3-profile-web-token-path }}
          aws configure set web_identity_token_file "${{ inputs.s3-profile-web-token-path }}" --profile ${{ inputs.s3-profile-name }}

    # - name: inject
    #   uses: rlespinasse/github-slug-action@v3.x
    - name: verify
      run: aws sts get-caller-identity

    - name: tf-setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.0
    
    - name: tf-init
      run: terraform init

    - name: tf-plan
      run: terraform plan -out=plan.tfout
    
    - name: store-plan
      uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: ./plan.tfout
      
    # - name: move-lock
    #   working-directory: ${{ inputs.working-directory }}
    #   run: cp ./.terraform.lock.hcl /home/runner/work/{REPO_NAME}/{REPO_NAME}/.terraform.lock.hcl

    # - name: store-lock
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: tf-lock
    #     path:  /home/runner/work/{REPO_NAME}/{REPO_NAME}/.terraform.lock.hcl
    #     include-hidden-files: true

  manual-approval:
    name: manual-approval
    runs-on: ubuntu-latest
    needs: tf-plan
    if: success()

    permissions:
      issues: write
      contents: read
    
    steps:
    - name: wait-for-approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.Token }}
        approvers: jatcod3r
        minimum-approvals: 1
        issue-title: "Manual Approval Required for `tf apply`."
        issue-body: "Please approve/deny the deployment."
        exclude-workflow-inititator-as-approver: false

