name: TF CI/CD

on:
  workflow_call:
    inputs:
      approvers:
        required: false
        type: string
        default: ${{ vars.APPROVERS }}
      working-directory:
        required: true
        type: string
      default-audience:
        type: string
        default: sts.amazonaws.com
        required: false
      s3-profile-name:
        type: string
        required: false
        default: demo-profile
      s3-profile-web-token-path:
        type: string
        default: /tmp/web_identity_token_file
        required: false
      ENV_VARS:
        type: string
        required: false
        default: ""
    secrets: 
      DEFAULT_ROLE:
        required: false
      DEFAULT_REGION:
        required: false
      S3_ROLE:
        required: false
      S3_REGION:
        required: false

jobs: 
  tf-validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: add-custom-env
      run: echo '${{ inputs.ENV_VARS }}' >> $GITHUB_ENV

    - name: setup-default
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        audience: ${{ inputs.default-audience }}
        aws-region: ${{ secrets.DEFAULT_REGION }}
        role-to-assume: ${{ secrets.DEFAULT_ROLE }}

    - name: setup-s3-profile
      run: |
          aws configure set region ${{ secrets.S3_REGION }} --profile ${{ inputs.s3-profile-name }}
          aws configure set role_arn ${{ secrets.S3_ROLE }} --profile ${{ inputs.s3-profile-name }}
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > ${{ inputs.s3-profile-web-token-path }}
          aws configure set web_identity_token_file "${{ inputs.s3-profile-web-token-path }}" --profile ${{ inputs.s3-profile-name }}

    - name: tf-setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.0
    
    - name: tf-init
      run: terraform init

    # - name: tf-plan
    #   run: terraform plan -out=plan.tfout
    
    # - name: store-plan
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: tf-plan
    #     path: ./plan.tfout

    - name: tf-test
      run: terraform test

  manual-approval:
    name: manual-approval
    runs-on: ubuntu-latest
    needs: tf-validate
    if: success()

    permissions:
      issues: write
      contents: read
    
    steps:
    - name: wait-for-approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.Token }}
        approvers: ${{ inputs.approvers }}
        minimum-approvals: 1
        issue-title: "Manual Approval Required for `tf apply`."
        issue-body: "Please approve/deny the deployment."
        exclude-workflow-inititator-as-approver: false

